---
- hosts: localhost
  sudo: yes
  tasks:
    - name: Add RPMFusion free Repo
      yum: name=http://download1.rpmfusion.org/free/fedora/rpmfusion-free-release-22.noarch.rpm state=present update_cache=yes disable_gpg_check=yes
      ignore_errors: yes
    - name: Add RPMFusion nonfree Repo
      yum: name=http://download1.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-22.noarch.rpm state=present update_cache=yes disable_gpg_check=yes
      ignore_errors: yes
    - name: Install base packages
      yum: name={{item}} state=present
      with_items:
        - transmission-remote-gtk
        - iftop
        - iotop
        - htop
        - vim
        - git
        - etckeeper
        - keepassx
        - nmap
        - kupfer
        - yum-plugin-remove-with-leaves
        - trash-cli
        - wget
        - net-tools
        - nmap-frontend
        - wireshark
        - sudo
        - nmon
        - ike
        - zsh
        - terminus-fonts
        - cryptkeeper
        - pandoc
        - ncdu
        - pwgen
        - ipcalculator
        - aria2
        - artwiz-aleczapka-fonts
        - w3m
        - w3m-img
        - trickle
        - tig
        - unrar
        - sshfs
        - mc
        - rdesktop
        - pavucontrol
        - python-pip
        - gnome-tweak-tool
        - strace
        - terminator
        - yumex-dnf
        - NetworkManager-openvpn
        - NetworkManager-openvpn-gnome
        - duply
        - newsbeuter
        - pv
        - thunderbird-enigmail
        - kpcli
        - python-dnf-plugins-extras-tracer
    - name: Install Chromium repo
      get_url: url=https://repos.fedorapeople.org/repos/spot/chromium-stable/fedora-chromium-stable.repo dest=/etc/yum.repos.d/fedora-chromium-stable.repo
    - name: Install Chromium repo GPG key
      get_url: url=https://repos.fedorapeople.org/repos/spot/chromium-stable/spot.gpg dest=/etc/pki/rpm-gpg/spot.gpg
    - name: Install Chromium
      yum: name=chromium state=present
    - name: Install Google Chrome
      yum: name=https://dl.google.com/linux/direct/google-chrome-stable_current_x86_64.rpm state=present
    - name: Install RPM tools
      yum: name={{item}} state=present
      with_items:
        - wget
        - rpm-build
        - yum-utils
        - rpmdevtools
    - name: Install web tools
      yum: name=firefox state=present
    - name: Install development tools
      yum: name={{item}} state=present
      with_items:
        - make
        - gitg
        - git
        - vim-X11
        - meld
        - ShellCheck
    - name: Install group Development Tools
      yum: name="@Development Tools" state=present
    - name: Install web development tools
      yum: name={{item}} state=present
      with_items:
        - rubygems
        - ruby-devel
        - rubygem-RedCloth
        - nodejs
    - name: Install Jekyll
      gem: name=jekyll state=present
    - name: Install LibreOffice
      yum: name="@Libreoffice" state=present
    - name: Install office applications
      yum: name={{item}} state=present
      with_items:
        - freemind
        - jortho-dictionary-de
        - cups-pdf
        - calibre
        - pdfmod
    - name: Install communication applications
      yum: name={{item}} state=present
      with_items:
        - thunderbird
        - pidgin
        - pidgin-otr
    - name: Install Media tools
      yum: name={{item}} state=present
      with_items:
        - vlc
        - youtube-dl
        - ffmpeg
    - name: Install Docker
      yum: name=docker-io state=present
    - name: Enable and Restart Docker daemon
      service: name=docker enabled=yes state=started
      ignore_errors: yes
    - name: Install Adobe Flash repo
      yum: name=http://linuxdownload.adobe.com/adobe-release/adobe-release-x86_64-1.0-1.noarch.rpm state=present
    - name: Install Adobe Flash
      yum: name=flash-plugin state=present
    - name: Install ownCloud client repo
      get_url: dest=/etc/yum.repos.d/owncloud-client.repo url=http://download.opensuse.org/repositories/isv:/ownCloud:/desktop/Fedora_22/isv:ownCloud:desktop.repo
    - name: Install ownCloud client
      yum: name=owncloud-client state=present
    - name: Install Codecs
      yum: name={{item}} state=present
      with_items:
        - gstreamer1-plugins-bad-freeworld
        - gstreamer1-plugins-good
        - gstreamer1-plugins-ugly
    - name: Install YUM DNF data migration plugin for DNF
      yum: name=python-dnf-plugins-extras-migrate state=present
    - name: Migrate YUM data to DNF
      shell: command="/usr/bin/dnf-2 migrate"
      sudo: yes
    - name: Install sysdig repo
      get_url: dest=/etc/yum.repos.d/draios.repo url=http://download.draios.com/stable/rpm/draios.repo
    - name: Import sysdig repo GPG key
      rpm_key: key=https://s3.amazonaws.com/download.draios.com/DRAIOS-GPG-KEY.public state=present
    - name: Install sysdig
      yum: name=sysdig state=present
    - name: Download Skype RPM
      get_url: url=http://www.skype.com/go/getskype-linux-beta-fc10 dest=/var/tmp/skype.rpm sha256sum=9011f4cbc8e7c484e55d2277b3c3503280d09b88bfadda3f447281169abdf924
    - name: Install Skype
      yum: name=/var/tmp/skype.rpm state=installed
    - name: Install VirtualBox
      tags: testme
      command: dnf install -y VirtualBox
    - name: Install Kernel Source
      tags: testme
      yum: name=kernel-devel state=present
    - name: Build VirtualBox Kernel Modules
      tags: testme
      command: /etc/init.d/vboxdrv setup
    - name: Install Vagrant
      yum: name={{ item }} state=installed
      with_items:
        - vagrant
        - vagrant-lxc
    - name: Download Atom RPM
      get_url: url=https://atom.io/download/rpm dest=/var/tmp/atom.rpm sha256sum=e605f63f0ce77d5694722c54b33ea61c48115c9c32c4a00f763499cf84872616
    - name: Install Atom
      yum: name=/var/tmp/atom.rpm state=installed
