---
- hosts: localhost
  sudo: yes
  tasks:
    - name: Add RPMFusion free Repo
      dnf: name=http://download1.rpmfusion.org/free/fedora/rpmfusion-free-release-23.noarch.rpm state=present disable_gpg_check=yes
      ignore_errors: yes
    - name: Add RPMFusion nonfree Repo
      dnf: name=http://download1.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-23.noarch.rpm state=present disable_gpg_check=yes
      ignore_errors: yes
    - name: Install base packages
      dnf: name={{item}} state=present
      with_items:
        - transmission-remote-gtk
        - iftop
        - iotop
        - htop
        - vim
        - git
        - etckeeper
        - keepassx
        - nmap
        - kupfer
        - trash-cli
        - wget
        - net-tools
        - nmap-frontend
        - wireshark-gnome
        - sudo
        - nmon
        - ike
        - zsh
        - terminus-fonts
        - cryptkeeper
        - pandoc
        - ncdu
        - pwgen
        - ipcalculator
        - aria2
        - artwiz-aleczapka-fonts
        - w3m
        - w3m-img
        - trickle
        - tig
        - sshfs
        - mc
        - rdesktop
        - pavucontrol
        - python-pip
        - gnome-tweak-tool
        - strace
        - terminator
        - NetworkManager-openvpn
        - NetworkManager-openvpn-gnome
        - duply
        - newsbeuter
        - pv
        - thunderbird-enigmail
        - kpcli
        - python-dnf-plugins-extras-tracer
        - guake
        - virt-manager
    - name: add heichblatt to @wireshark
      user: name=heichblatt groups=wireshark append=yes
    - name: Install Google Chrome
      dnf: name=https://dl.google.com/linux/direct/google-chrome-stable_current_x86_64.rpm state=present
    - name: Install RPM tools
      dnf: name={{item}} state=present
      with_items:
        - wget
        - rpm-build
        - rpmdevtools
    - name: Install web tools
      dnf: name=firefox state=present
    - name: Install development tools
      dnf: name={{item}} state=present
      with_items:
        - make
        - gitg
        - git
        - vim-X11
        - meld
        - ShellCheck
    - name: Install group Development Tools
      dnf: name="@Development Tools" state=present
    - name: Install web development tools
      dnf: name={{item}} state=present
      with_items:
        - rubygems
        - ruby-devel
        - rubygem-RedCloth
        - nodejs
    - name: Install Jekyll
      gem: name=jekyll state=present
    - name: Install LibreOffice
      dnf: name="@Libreoffice" state=present
    - name: Install office applications
      dnf: name={{item}} state=present
      with_items:
        - freemind
        - jortho-dictionary-de
        - cups-pdf
        - calibre
        - pdfmod
    - name: Install communication applications
      dnf: name={{item}} state=present
      with_items:
        - thunderbird
        - pidgin
        - pidgin-otr
    - name: Install Media tools
      dnf: name={{item}} state=present
      with_items:
        - vlc
        - youtube-dl
        - ffmpeg
    - name: Install Docker
      dnf: name=docker-io state=present
    - name: add group docker
      group: name=docker state=present
    - name: add heichblatt to @docker
      user: name=heichblatt groups=docker append=yes
    - name: Enable and Restart Docker daemon
      service: name=docker enabled=yes state=started
      ignore_errors: yes
    - name: Install Adobe Flash repo
      dnf: name=http://linuxdownload.adobe.com/adobe-release/adobe-release-x86_64-1.0-1.noarch.rpm state=present
    - name: Install Adobe Flash
      dnf: name=flash-plugin state=present
    - name: Install ownCloud client repo
      get_url: dest=/etc/yum.repos.d/owncloud-client.repo url=http://download.opensuse.org/repositories/isv:/ownCloud:/desktop/Fedora_22/isv:ownCloud:desktop.repo
    - name: Install ownCloud client
      dnf: name=owncloud-client state=present
    - name: Install Codecs
      dnf: name={{item}} state=present
      with_items:
        - gstreamer1-plugins-bad-freeworld
        - gstreamer1-plugins-good
        - gstreamer1-plugins-ugly
    - name: Install YUM DNF data migration plugin for DNF
      dnf: name=python-dnf-plugins-extras-migrate state=present
    - name: Migrate YUM data to DNF
      shell: command="/usr/bin/dnf-2 migrate"
      sudo: yes
    - name: Install sysdig repo
      get_url: dest=/etc/yum.repos.d/draios.repo url=http://download.draios.com/stable/rpm/draios.repo
    - name: Import sysdig repo GPG key
      rpm_key: key=https://s3.amazonaws.com/download.draios.com/DRAIOS-GPG-KEY.public state=present
    - name: Install sysdig
      dnf: name=sysdig state=present
    - name: Download Skype RPM
      get_url: url=http://www.skype.com/go/getskype-linux-beta-fc10 dest=/var/tmp/skype.rpm sha256sum=9011f4cbc8e7c484e55d2277b3c3503280d09b88bfadda3f447281169abdf924
    - name: Install Skype
      dnf: name=/var/tmp/skype.rpm state=installed
    - name: Install Vagrant
      dnf: name={{ item }} state=installed
      with_items:
        - vagrant
        - vagrant-lxc
    - name: Download Atom RPM
      get_url: url=https://atom.io/download/rpm dest=/var/tmp/atom.rpm sha256sum=b5dc489db12d08dd7d161686a0b8e5c6c4a50fe4e1252cf05e5aec44a658346e
    - name: Install Atom
      dnf: name=/var/tmp/atom.rpm state=installed
    # - name: fetch virtualbox repo
    #   get_url: url=http://download.virtualbox.org/virtualbox/rpm/fedora/virtualbox.repo dest=/etc/yum.repos.d sha256sum=6544572ace630c061d595294d4f14c574fc94e75784d19f5518337bd6be811ed
    # - name: import virtualbox rpm gpg key
    #   shell: rpm --import https://www.virtualbox.org/download/oracle_vbox.asc
    # - name: install VirtualBox-4.3
    #   dnf: name=VirtualBox-4.3 state=present
    # - name: add heichblatt to @vboxusers
    #   user: name=heichblatt groups=vboxusers append=yes